name: gurps_character_creation
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  provider: ^6.1.2
  gap: ^3.0.1
  uuid: ^4.4.2
  flutter_svg: ^2.0.16
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/Traits/BasicSet.json
    - assets/Skills/BasicSet.json
    - assets/Spells/magic.json
    - assets/spell_book.svg
