name: gurps_character_creation
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  provider: ^6.1.2
  gap: ^3.0.1
  uuid: ^4.4.2
  flutter_svg: ^2.0.16
  file_picker: ^8.1.7
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/favicon.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/favicon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/favicon.png"

flutter_native_splash:
  color: "#eeeeee"
  color_dark: "#282b30"
  background_image: "assets/favicon.png"

  android_12:
    color: "#eeeeee"
    color_dark: "#282b30"
    image: "assets/android12favicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/Traits/BasicSet.json
    - assets/Skills/BasicSet.json
    - assets/Spells/magic.json
    - assets/Equipment/Mellee_Weapons/BasicSet.json
    - assets/Equipment/Ranged_Weapons/BasicSet.json
    - assets/Equipment/Armor/BasicSet.json
    - assets/spell_book.svg
    - assets/favicon.png
    - assets/android12favicon.png
