const int MAX_MOBILE_WIDTH = 612;
const int MIN_DESKTOP_WIDTH = 856;

const int MAX_DESKTOP_COLUMNS = 4;
const int MAX_TABLET_COLUMNS = 4;

const double DESKTOP_COLUMNS_SPACING = 16 + 8;
const double DESKTOP_ROWS_SPACING = 24;

const double MOBILE_HORIZONTAL_PADDING = 16;
const double MOBILE_VERTICAL_PADDING = 4;

const double DESKTOP_HORIZONTAL_PADDING = 32;
const double DESKTOP_VERTICAL_PADDING = 16;

const double MAX_DESKTOP_CONTENT_WIDTH = 896;
